### ISSUE TITLE
ReactionAdded type may not have the "name" field

### ISSUE THREAD

**Issue by kiyoto** [slack-rs/slack-rs-api#15]
Here is an example:

```js
{
    "type": "reaction_added",
    "user": "XXX",
    "item": {
        "type": "XXX",
        "channel": "XXX",
        "ts": "XXX"
    },
    "reaction": "+1",
    "item_user": "XXX",
    "event_ts": "XXX"
}
```

See https://github.com/slack-rs/slack-rs/issues/53

**Comment by kiyoto** [comment]
@mthjones It looks like this event is handled in `slack-rs`, not `slack-rs-api`. In general, what's the criterion for an API implementatino going into `slack-rs` as opposed to `slack-rs-api`?

**Comment by kiyoto** [comment]
Filed the PR on `slack-rs`. Closing this one.

**Comment by mthjones** [comment]
Good catch. :)

The split between `slack_api` and `slack-rs` is basically the split between the [web API methods](https://api.slack.com/methods) and the [RTM (websocket) support](https://api.slack.com/rtm) that Slack provides. There's some overlap in types returned, but unless they're specific to the RTM stuff they're implemented here and re-exported from `slack-rs`.
