### ISSUE TITLE
Item type's Message/File/Comment are different

### ISSUE THREAD

**Issue by kiyoto** [slack-rs/slack-rs-api#25]
Here's an example JSON message coming from Slack RTM when I add a reaction to a file upload.

``` js
{
    "type": "reaction_added",
    "user": "U03FD1E0J",
    "item": {
        "type": "file",
        "file": "F13BSAM9Q"
    },
    "reaction": "+1",
    "item_user": "U03FD1E0J",
    "event_ts": "1461565808.648052"
}
```

See https://api.slack.com/events/reaction_added. This means the current implementation of `Item` struct is buggy.

**Comment by BenTheElder** [comment]
This definitely needs to be corrected. From the docs "Embedded item nodes are more lightweight than the structures you'll find in reactions.list.", we'll need to make some new types for `Message`, `File`, and `FileComment` structures embedded in `reaction_added` events.

**Comment by mthjones** [comment]
Fixed with new codegen release. They all have their own types now.
