### ISSUE TITLE
UserProfile should have a display_name field.

### ISSUE THREAD

**Issue by remexre** [slack-rs/slack-rs-api#52]

**Comment by dten** [comment]
Is this for displaying a name outside of slack?
You should use `<user.id>` (the one starting #U) for linking to people in messages

**Comment by remexre** [comment]
No, it's what shows up as a result of doing that; I need the plain-text version because I'm display a table in a code block that needs to mention users. (If there's a way to do non-ascii-art tables or links to users in a code block, I'd be more than happy to use those instead).

**Comment by dten** [comment]
I use the attachments api for a table but I only small

https://api.slack.com/docs/message-attachments

The reason you're not supposed to use display name is it doesn't update when people change it but the links do. But yea you can't link in a code block

Can get it added if needed but slack suggest not to, and i think it's not in their docs page

**Comment by remexre** [comment]
Yeah, my table's got 5 columns by a whole bunch (<1000 for now) rows, so attachments are probably not a great fit. In the Slack room I'm testing in, there's a user whose name when @-mentioned is `bar`, where as their name in the user object is `foo`.

[The docs for the user object](https://api.slack.com/types/user) both mention `display_name` and recommend it's use.

**Comment by dten** [comment]
oh yea, hmm i must have misunderstood. will add it when I get the chance.

**Comment by dten** [comment]
#54 has these now
i noticed some users' `display_name`s come out as `""`, i think users that haven't logged in recently so watch out for that

**Comment by remexre** [comment]
Alright, thanks!
