### ISSUE TITLE
channels::info sometimes returns malformed response

### ISSUE THREAD

**Issue by clux** [slack-rs/slack-rs-api#79]
Can happen when the `latest` message has a `ts` formatted as a string:

```json
          "ts": "1570109136.344300",
```

but types.rs encodes it as:

```rust
    pub ts: Option<f32>,
```

leading to: `JSON error - MalformedResponse(Error("invalid type: string \"1570109136.344300\", expected f32", line: 1, column: 2342))`

**Comment by dten** [comment]
Do you know what type that was on? They vary if they're string or they're floats. I wonder if they're just wrong here in some places or slack are changing things

**Comment by dten** [comment]
Oh sorry you say that's channel info.

**Comment by clux** [comment]
Yeah, the `ts` type seems to vary, which is the strange thing. Maybe it's a slack api bug?

Ultimately, have been building from a fork where the [latest message on channel info has been commented out](https://github.com/clux/slack-rs-api/commit/673dc064405bcc74929cae10ce571c6254a798a8). Not sure how to deal with that type of inconsistency using serde.

**Comment by dten** [comment]
There's a PR about trying to fix these time stamps. I think it's just a mistake on slacks oart that is now hard to change

**Comment by DanielJoyce** [comment]
JS has limited float precious so perhaps these comeback as strings sometime to preserve precision for other languages

**Comment by dten** [comment]
this is fixed by the new Timestamp type https://github.com/slack-rs/slack-rs-api/releases/tag/v0.23.0
