### ISSUE TITLE
Async release

### ISSUE THREAD

**Issue by msdinit** [slack-rs/slack-rs-api#94]
Hi!
Sorry if an issue is not the preferred way of asking this type of question, but I wanted to ask if there is anything in particular that's blocking an async release?
I see that master branch is async, and with a cursory look through issues I couldn't find anything related to async as well.

The reason I'm asking is that I want to use your crate in an async environment, but feel reluctant to depend on a non-released version in case there are issues I'm unaware of.

**Comment by sts10** [comment]
It'd be great to have a fresh release sometime soon!

**Comment by dten** [comment]
Hey! it's a perfectly fine way to ask.
I've been using it in my own apps and I was letting it simmer a little in case any problems arose and then kind of forgot since it's been 100% fine and I've been otherwise busy.
Running a release now

**Comment by msdinit** [comment]
Thank you!
